name: check code

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  selene:
    name: selene
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: Roblox/setup-foreman@v1
      with:
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Run selene
      run: |
        selene .

    - uses: reviewdog/action-suggester@v1
      with:
        tool_name: selene

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: Roblox/setup-foreman@v1
      with:
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Run stylua
      run: |
        stylua .

    - uses: reviewdog/action-suggester@v1
      with:
        tool_name: stylua